title: <p align="center"> Harsha Kodlaya </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/harsha-kodlaya-979338b/">LinkedIn</a> |
  <a href="https://github.com/harshakk">GitHub</a>
  
  <br>   
  I'm an Engineering Leader in Data Science, Big Data, Spark, Machine learning & NLP domain.
  I have  around 20 years of industry experience with several domains and roles.
  <br>
  </p>



theme: jekyll-theme-minimal
