title: <p align="center"> Harsha Kodlaya </p>
logo: /assets/img/ProfilePic.jpg

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/harsha-kodlaya-979338b/">LinkedIn</a> |
  <a href="https://github.com/harshakk">GitHub</a>
  
  <br>   
  I'm an Engineering Leader in Big Data and Analytics, Databricks, Gen AI, Machine learning & NLP domain.
  I have about 20 years of industry experience with several domains and roles.
  <br>
  </p>



theme: jekyll-theme-minimal
